use pendzl::traits::Timestamp;

// NUMBERS
/// One thousand.
pub const E3_U128: u128 = 10_u128.pow(3);
/// One million.
pub const E6_U128: u128 = 10_u128.pow(6);
/// Hundred million.
pub const E8_U128: u128 = 10_u128.pow(8);
/// One milliard
pub const E12_U128: u128 = 10_u128.pow(12);

// TIME
/// A duration of one hour in milliseconds.
pub const ONE_HOUR: Timestamp = 60 * 60 * 1000;
/// A duration of one day in milliseconds.
pub const ONE_DAY: Timestamp = 24 * ONE_HOUR;
/// A duration of one year in milliseconds.
pub const ONE_YEAR: Timestamp = 365 * ONE_DAY;
/// A duration of the vesting period for contributors and founders - 4 years.
pub const VEST_DURATION: Timestamp = ONE_YEAR * 4;

// ALLOCATION - parts of 1000
/// A part of all tokens generated by Abax TGE Contract that is allocated to founders - 20%.
pub const PART_OF_FOUNDERS_E3: u16 = 200;
/// A part of all tokens generated by Abax TGE Contract that is allocated to foundation - 2%.
pub const PART_OD_FOUNDATION_E3: u16 = 20;

// ALLOCATION - instant release parts of 1000
/// A part of founders allocation that is instantly released - 20%
pub const INSTANT_FOUNDERS_RELEASE_E3: u16 = 200;
/// A part of contributors allocation that is instantly released - 40%
pub const INSTANT_CONTRIBUTOR_RELEASE_E3: u16 = 400;

/// A ratio of all allocation to contributors allocation; contributors have 20% resulating in ratio 5
pub const ALL_TO_PUBLIC_RATIO: u128 = 5; // 5:1

// BONUS
/// A bonus for using a referral code - 1% (total bonus is capped at 10%)
pub const BONUS_FOR_REFERRER_USE_E3: u16 = 10;
/// A maximal additional part received as bonus - 10%.
pub const BONUS_MAX_E3: u16 = 100;
/// An amount of tokens that must be contributed to get a 1% contribution bonus. 1000 Tokens
pub const BONUS_DENOMINATOR: u128 = 1000 * 10_u128.pow(6);

/// A part of the contribution that is additionally reserved for referrer.
pub const REWARD_FOR_REFERER_E3: u16 = 20;
